language: node_js

node_js:
- '10'
install:
- npm i

script:
- npm run build
- npm run test

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJARDOMZDSZO4VQDQ
  secret_access_key:
    secure: cFP6zopvAkKZvODf2uSHEGN83M5OHJIj8Yy3ThgYqdOm9KxYI8NJ32gAnafcUUY0sMl0jB2XYVlittkF5nBmBqpPZnYlMIRxG23DNytECoaVyaYlIbFhw19fOvHVHyaXqlclJkacs/ueFdzvNo0GBKsuoL8R8yarJv+nc0OLVKq0TITh2SgyaPTdFJyWUOcMMK5YVyycDYc9oVvZjQInlc4CFMoDA5YbBKM4EX8D9O53mrOh2s4c74PTWJnzm0XbFFfcbKcXrxcNi6X0GxujUz31UvYALr/8c3rprQleI55dhhzUf6BIyMXUbR0SJEmcQEJnYBr97XZcddHIySnu4lb01QFOCTOgPmbgj1Xg+TNi0QRcFouuThNMpFcVsT9hnnfRmyFp2f41lkN4bVYQre5UGEiN5Csn/+kPnyKU+T2ClsynOZkYF1R2TpCKDCGHSL3x+taPsY6o0goJVI1lRLEZSDUn/aDWb/uR0yQSMK/EKNUFrRuXsBZ/AWUWgXLn2Haf66tK6I7Ar3pCiti1Y2oI7aBhqjbQIWZU7OyRzN8mT7AYzHehwW2FprbFozcY2TiHcMwaNdYZUTBc0XzWo6Mdn04tt0KUBjP5VZ27usPCFT9JVZ2bH7XJvwmn7ShTvkxgtJlS3onrZfmGkNSkPs39WiG8N/6e4SzEWBPzJ40=
  bucket: cicd-demo-opensource
  acl: public_read
  region: eu-west-2
  on:
    repo: kouks/cicd-demo
    branch: master
